# Use root/example as user/password credentials
version: '3.1'

services:
  forum:
    image: php:7.3.5-apache
    depends_on:
      - db
    restart: always
    ports:
      - 80:80
    volumes:
      - ~/Documents/projects/testPHP/:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - ~/Documents/projects/testMySQL/:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
