# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ../www/:/var/www
    ports:
      - 80:80
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - local
    depends_on:
      - forum
      - db
      - adminer

  forum:
    image: php:7.3.5-apache
    depends_on:
      - db
    restart: always
    ports:
      - 8100:80
    volumes:
      - ~/Documents/projects/testPHP/:/var/www/html/
    networks:
      - local

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    volumes:
      - ~/Documents/projects/testMySQL/:/var/lib/mysql
    networks:
      - local

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    networks:
      - local

networks:
  local:
    driver: bridge
